# Measurement paras configs editor

Instrument_IP = ' 192.168.1.10 ' # type in str 

cool_down_date = ' 20241110 ' # type in str 

cool_down_dr = ' dr2 ' # type in str 

how_many_couplers = 4       # type in <class 'int'>

how_many_qubits =  5      # type in <class 'int'>

sample_name = ' 5Q4C_Test ' # type in str 

