# Please avoid the space between your world, you can use '_' replace it if it's necessary.
# Measurement paras configs editor

avg_n =        # type in  <class 'int'>
machine_IP = '  ' # type in str 
list_sampling_func = '  ' # linspace or arange 

[q0]
  freq_range =        # type in list, rule: [ start, end, pts ] or [ fixed value ]


[q1]
  freq_range =        # type in list, rule: [ start, end, pts ] or [ fixed value ]


